travis:
  secure:
    BINSTAR_TOKEN: CkkZaSvg4oNcc/PKYhpFlBa8hF3MVKpNJllEPS1TRuxIENriP/jLkayS5HL7VLdRO4gfX+23b0FuJ1MmIym3ZwkEIsk/jrD6Rj9mT6hDlUQrY0GVYRgpb3DXFjFRunblZy0mRM57stho1F8rmQuUIBT02BT2NgzEG7oL2hUaGV+OGw7GsSM8arwWk6OFLO4iAWAMLn/qlgDo5bmEr96lwAjxYlm+0LZLb3f8U7Uyt+BZjRR+6b4CoRlP/tFF77dr4zd8h7hB6N4IwPBydc65BmVt77E4ETg5wiSULQAi7/uTtQW64EyOELlVzWvdbimxIKUympkIqJxpMSUayNPi5JuAXRgDITVBgRCnva/FpHYMUHKbie4lIjltOO7xrFxmLoR3pkQZJPq/Hzp+WS+OU+sSmbSRQsE5RksvZlt6F8RZO47fYmpFpyjdGEHA0wxsyZPXLDZNrMmkwwg0W/RRnF39H8ElFKNlkRNZkclg2rAOud2vQr+poF4j48m/9OVfNGAzSecG+vao7eE58jE4+Mq91idRzDxnmd+OhTLQrGNc7ydJ4PLr/RXW+5GT9tFIsmCNRgCOWU9EO62HRy7jW5495wnsr2BmYggbAjxKWPs+6F1kJmQOqoXjyfvCepiZGSohng5VdFJNP/oEyUhnhq7BWJ8gqCHlgOMVtlAuW5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
